# Introduction

One of the most important libraries for scientific work in Python is numpy. It provides methods and algorithms for numerical calculations and is based on many established libraries written in C and Fortran. This makes working with Python much easier and has contributed significantly to its success in science. Instead of writing detailed hardware-related code, we often only write glue code, which describes the data flow and provides the information as required by the efficient libraries.

In a way, numpy builds a bridge between the easily readable and maintainable Python code and the hardware-related efficiency. One of the ways this is achieved is that numpy has its own data structure that is not part of the standard library: the array. The easiest way to visualise this is as a list, which may be concatenated to describe a matrix or a higher tensor.

In addition to efficient data types, numpy provides a variety of specialised functions: from linear algebra, to interpolation, polynomial functions, Fourier transformations, random numbers and much more.

'numpy' must be explicitly loaded as a module, as it is not part of the standard functionality. The convention is that it is loaded as follows:

In [27]:
import numpy as np

This loads numpy under the alias np. Functions or data types with np used in the following therefore require this import. For the sake of readability, however, this import is no longer listed in later code examples.

In order to utilise the special efficiency of numpy, it is important to use the internal functions. As soon as a regular Python loop is used, the advantages offered by the library are lost.

# Arrays and lists

The central data structure in numpy is the np.ndarray (array for short). Unlike a list, an array can only contain one homogeneous data type for efficiency reasons. This allows a special storage of the data, which is essential for the efficient implementation of the algorithms in numpy and the underlying libraries.

A data type within the array is called np.dtype. This dtype is close in content to the data types that we already know from Python itself: integers and decimal numbers are available here again. While the decimal numbers behave in the same way as in Python, it should be noted that (again for reasons of efficiency) the integers in numpy have a fixed value range. Frequently used data types and their restrictions are:

| Data type   | Range                                                 |
|-------------|-------------------------------------------------------|
| `np.int8`   | -128 to 127                                           |
| `np.int32`  | -2147483648 to 2147483647                             |
| `np.int64`  | -9223372036854775808 to 9223372036854775807           |
| `np.uint8`  | 0 to 255                                              |
| `np.uint16` | 0 to 65535                                            |
| `np.uint32` | 0 to 4294967295                                       |
| `np.uint64` | 0 to 18446744073709551615                             |
| `np.float64`| 64-bit IEEE 754 (double precision)                    |


It is easy to create arrays from lists:

In [28]:
values = [1,2,3,4,5]
array = np.array(values)
print(array)

[1 2 3 4 5]


A multidimensional array is created for nested lists of the same length:

In [29]:
values = [[1,2,3], 
          [4,5,6],
          [7,8,9]]
array = np.array(values)
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


The size of an array can be queried using the .shape property:

In [30]:
values = [[1,2,3],
          [4,5,6]]
array = np.array(values)
print(array.shape)

(2, 3)


Here the number of rows comes first, then the number of columns. In numpy, a dimension is referred to as axis. Conversely, an array can also be converted into a list:

In [31]:
values = [[1,2,3],
          [4,5,6]]
array = np.array(values)
print (array.tolist())

[[1, 2, 3], [4, 5, 6]]


Many operations are performed on the original data as long as possible without copying it. This is called numpy views. For example, the transpose of a matrix is accessible as a view via .T:

In [32]:
values = [[1,2,3],
          [4,5,6]]
array = np.array(values)
print (array.T)

[[1 4]
 [2 5]
 [3 6]]


Or the shape of an array can be changed using reshape, which also creates a view, i.e. the data is not copied again.

In [33]:
values = [1,2,3,4]
array = np.array(values)
print (array)
reshaped = array.reshape(2,2)
print (reshaped)

[1 2 3 4]
[[1 2]
 [3 4]]


A variety of functions can be evaluated on each array, e.g.

In [34]:
np.arange(4).sum()

6

In [35]:
np.arange(4).mean()

1.5

In [36]:
np.arange(4).std()

1.118033988749895

In [37]:
np.arange(4).min()

0

In [38]:
np.arange(4).max()

3

# Array generators

Of course, you can first create a list like previously and then convert it into an array. However, this is not very efficient on the one hand and not particularly convenient on the other. Here, we get to know the most common methods for generating arrays of certain properties.

### Sequences

We have already learnt about the built-in function range, which generates a sequence of numbers. In numpy there are arange (array range), linspace (linearly spaced), and logspace (logarithmically spaced), each of which generates a sequence of numbers.

In [39]:
np.arange(4)

array([0, 1, 2, 3])

In [40]:
np.arange(0,4,1)

array([0, 1, 2, 3])

The arguments of arange are the same as for range(). Unlike there, however, decimal numbers are possible as arguments. If an integer is passed, the array elements are also integers. If a decimal number is passed, the array elements are also decimal numbers.

In [41]:
np.arange(0,4,1)

array([0, 1, 2, 3])

In [42]:
np.arange(0,4,1.)

array([0., 1., 2., 3.])

While arange generates a sequence based on the step size, linspace generates an array based on the number of steps. With linspace the entries have a constant distance to each other. With logspace, the entries are distributed logarithmically.

In [43]:
np.linspace(0,4,5)

array([0., 1., 2., 3., 4.])

In [44]:
np.logspace(0,1,3)

array([ 1.        ,  3.16227766, 10.        ])

### Structured arrays

Equations often contain matrices that have a certain structure. The identity matrix, for example, can be created as follows:

In [45]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

The only argument here is the size of the matrix. We obtain the zero matrix with:

In [46]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

If the diagonal is known, you can also create the diagonal matrix:

In [48]:
np.diag(np.identity(3))

array([1., 1., 1.])

### Random numbers

In many places, (pseudo-)random numbers allow an elegant solution to problems. numpy.random contains a variety of functions to generate random numbers. The functions are sorted according to the distribution from which they are drawn. 

In [51]:
np.random.uniform() # a number between 0 and 1

0.08273580373936018

In [50]:
np.random.normal() # a number from a normal distribution

1.3560163495393838

The functions can also generate whole arrays with random numbers:

In [52]:
np.random.uniform(size=3)

array([0.40606387, 0.8297285 , 0.86276163])

In [53]:
np.random.uniform(size=(2,3))

array([[0.44394272, 0.30996639, 0.64150328],
       [0.2186398 , 0.02689622, 0.30838047]])

 The argument size corresponds to the size of the array to be generated, i.e. what you would expect in array.shape.

In [54]:
np.random.uniform(size=(4,5))

array([[0.6889704 , 0.40026711, 0.89840531, 0.6271202 , 0.32299959],
       [0.89805997, 0.10332312, 0.52908612, 0.04894618, 0.63556351],
       [0.87690537, 0.85399721, 0.03502729, 0.63943043, 0.1186088 ],
       [0.05765912, 0.65620894, 0.845761  , 0.66898519, 0.99256004]])

# Broadcasting

Mathematical operations are applied to arrays in numpy in the same way as we are used to in mathematics. If the operands have different (formally incompatible) forms, the smaller of the two operands is added according to a fixed scheme so that the operation becomes possible. This process is called broadcasting.

The simplest case is the addition of a scalar to an array. Here, the scalar is added to all elements of the array:

In [55]:
np.array([1,2,3]) + 1

array([2, 3, 4])

In [58]:
np.array([1,2,3,4,5]) + np.array([6,7,8,9,10])

array([ 7,  9, 11, 13, 15])

The method is also used in higher dimensions and is carried out in the following steps:

    The dimensions of two arrays are compared pairwise in reverse order.
    For each pair, either both dimensions must be the same or one of the two dimensions must have the value 1. If both dimensions are equal, the operation is performed element by element. If one of the two dimensions is 1, the array in this dimension is filled with copies of the only value in the array and the operation is then carried out element by element.
    For all remaining dimensions, the array with the smaller dimension is completed using dimensions with only one element so that the number of dimensions matches.

An example:

In [61]:
np.identity(3) + np.array([1,2,3])

array([[2., 2., 3.],
       [1., 3., 3.],
       [1., 2., 4.]])

Here, the array np.identity(3) has the dimensions (3, 3) and the array np.array([1, 2, 3]) has the dimensions (3,). The dimensions are compared in pairs:

In [62]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
np.array([1,2,3])

array([1, 2, 3])

This logically corresponds to three copies of the second array in the first dimension:

In [64]:
np.identity(3) +  np.array([1,2,3])

array([[2., 2., 3.],
       [1., 3., 3.],
       [1., 2., 4.]])

Since the copy is made along the first axis, the row vectors are identical. If you want to have identical column vectors instead, you must instruct numpy to make the copy along the second axis by inserting an artificial axis in the second operand. This can be done with reshape, for example:

In [65]:
np.identity(3) + np.array([1, 2, 3]).reshape(3, 1)

array([[2., 1., 1.],
       [2., 3., 2.],
       [3., 3., 4.]])

This is formally equivalent to:

In [66]:
np.identity(3) + np.array([[1], [2], [3]])

array([[2., 1., 1.],
       [2., 3., 2.],
       [3., 3., 4.]])

We will get to know an elegant way with np.newaxis later.

# Linear algebra

Elementwise operations are not always what we expect. We have to distinguish between a two-dimensional array and the interpretation of it as a matrix. For example, the product of two matrices is not the element-wise product, but the product of the rows of the first matrix with the columns of the second matrix. This is why there are special operators for linear algebra.

In [67]:
np.arange(4) * np.arange(4)

array([0, 1, 4, 9])

In [68]:
np.dot(np.arange(4), np.arange(4))

14

In [69]:
np.outer(np.arange(4), np.arange(4))

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

The matrix multiplication is performed with @:

In [72]:
A = np.arange(9).reshape(3,3)
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [71]:
A * A

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [73]:
A @ A

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

The norm of a vector can be calculated with np.linalg.norm:

In [74]:
np.linalg.norm(np.arange(3))

2.23606797749979

Eigenvalues and eigenvectors as well as the determinant of a matrix can be calculated with np.linalg.eig:

In [77]:
A = np.array([[2,1], [1,2]])

In [78]:
np.linalg.eig(A).eigenvalues

array([3., 1.])

In [79]:
np.linalg.eig(A).eigenvectors

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [80]:
np.linalg.det(A)

2.9999999999999996

**NumPy** has a wide variety of mathematical functions, and these functions can take the following as input parameters:

- Numbers: _**int**_, _**float**_.
- **Lists** or **Arrays**.

| Functions     | Description                                     |
|---------------|-------------------------------------------------|
| np.max()      | Returns the maximum of an array.                |
| np.min()      | Returns the minimum of an array.                |
| np.sum()      | Returns the sum of the elements in an array.    |
| np.abs()      | Returns the absolute value of the elements in an array. |
| np.round()    | Function to round numbers.                      |
| np.power()    | Function to apply power.                        |
| np.sqrt()     | Square root.                                    |
| np.log2()     | Logarithm base 2 function.                      |
| np.log10()    | Logarithm base 10 function.                     |
| np.log()      | Natural logarithm or base e.                    |
| np.sin()      | Sine function.                                  |
| np.cos()      | Cosine function.                                |
| np.tan()      | Tangent function.                               |
| np.arcsin()   | Arcsine function.                               |
| np.arccos()   | Arccosine function.                             |
| np.arctan()   | Arctangent function.                            |


If the input parameter is a **list** or **array**, the function will transform all the elements and return an **array**.

# (Advanced) Indexing

To write compact code where the operations stay within numpy without writing control structures in Python, we need a way to convey numpy's intent. The tool for this is clever indexing.

Firstly, individual elements can be indexed in exactly the same way as with lists:

In [81]:
a = np.array([1,2,3,4,5])

In [82]:
a[0]

1

In [85]:
a[2]

3

In [83]:
a[-1]

5

Areas can be indexed with slices:

In [84]:
a = np.array([1,2,3,4,5])
a[1:3]

array([2, 3])

The first element to be included and the first element to be excluded are specified: i.e. including the second element with index 1 but without the fourth element with index 3. If a value is omitted, the first or last element is assumed. If both delimiters are omitted, the entire array is copied:

In [ ]:
a = np.array[(1,2,3,4,5)]

In [93]:
a[:3]

array([1, 2, 3])

In [89]:
a[:]

array([1, 2, 3, 4, 5])

In [90]:
a[1:]

array([2, 3, 4, 5])

In multi dimensions, the boundaries are separated by commas:

In [96]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [95]:
a[1:3, 1:3]

array([[4, 5],
       [7, 8]])

The same applies to a single element:

In [99]:
a = np.arange(9).reshape(3,3)
print(a)
a[1,1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


4

This technique can also be used for assignments:

In [100]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [102]:
a[0,0] = 42
print(a)

[[42  1  2]
 [ 3  4  5]
 [ 6  7  8]]


In [104]:
a[1:, :] = 0
print(a)

[[42  1  2]
 [ 0  0  0]
 [ 0  0  0]]


But what if I have a list of elements that I want to extract? Unlike lists, numpy also accepts lists as indices:

In [109]:
a = np.arange(9)**2
print(a)

[ 0  1  4  9 16 25 36 49 64]


In [110]:
a[[1,3,5]]

array([ 1,  9, 25])

Lists (or arrays) of truth values are also possible:

In [111]:
a = np.arange(3)**2
print(a)

[0 1 4]


In [112]:
a[[False, True, True]]

array([1, 4])

This is particularly helpful if you want to apply a condition to the array and want to use broadcasting:

In [116]:
a = np.arange(9)
print(a)

[0 1 2 3 4 5 6 7 8]


In [117]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True])

In [118]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

You have to be careful in multi dimensions because not all combinations of the several specified indices are possible:

In [120]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [121]:
a[[0,1], [1,2]]

array([1, 5])

If you actually want all combinations from the two lists instead, you need np.ix_:

In [122]:
a = np.arange(9).reshape(3,3)
a[np.ix_([0,1], [1,2])]

array([[1, 2],
       [4, 5]])

A new dimension can be added with np.newaxis:

In [124]:
a = np.arange(3)
print(a)

[0 1 2]


In [125]:
a[:, np.newaxis]

array([[0],
       [1],
       [2]])

This is particularly useful for replacing loops

#### Indexing as a loop replacement

Suppose we want to calculate the pairwise distances between particles in 1D. In normal Python, this would be a nested loop:

In [127]:
def pairwise_distances_python(positions: list[float]):
    distances = []
    for i, p1 in enumerate(positions):
        row = []
        for j, p2 in enumerate(positions):
            row.append(abs(p1-p2))
        distances.append(row)
    return distances

pairwise_distances_python([1,2,3])

[[0, 1, 2], [1, 0, 1], [2, 1, 0]]

The principle could also be applied to 'numpy':

In [129]:
def pairwise_distances_numpy(positions: np.ndarray):
    return np.abs(positions[:, np.newaxis] -  positions[np.newaxis, :])

The trick here is that the first sub-expression positions[:, np.newaxis] creates a 2D array that stores the positions in the rows. The second positions[np.newaxis, :] creates a 2D array containing the positions in the columns. The subtraction is now performed with broadcasting, in which the first array is copied to all rows of a matrix, while the second array is copied to all rows. The result is a matrix containing the differences of all pairs of positions. This corresponds to

array([[0, 0, 0],         array([[0, 1, 2],
       [1, 1, 1],    -           [0, 1, 2],
       [2, 2, 2]])               [0, 1, 2]])